<?php

namespace AppBundle\Repository;

/**
 * AgeEnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgeEnfantRepository extends \Doctrine\ORM\EntityRepository
{
}
