<?php

namespace AppBundle\Repository;

/**
 * TabletteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TabletteRepository extends \Doctrine\ORM\EntityRepository
{
}
