services:
    application_sonata_user.admin.user:
        class: Application\Sonata\UserBundle\Admin\UserAdmin
        arguments: [~, Application\Sonata\UserBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Utilisateurs }
        public: true
    application_sonata_user.admin.customer_user:
        class: Application\Sonata\UserBundle\Admin\CustomerUserAdmin
        arguments: [~, Application\Sonata\UserBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Utilisateurs }
        public: true

